-- { 'tpope/vim-surround' },
-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()" --}}}
require "skogix.impatient"
require "skogix.options"
require "skogix.plugins"
require "skogix.mappings"
require "skogix.autocommands"
require "skogix.colorscheme"
require "skogix.cmp"
require "skogix.telescope"
require "skogix.gitsigns"
require "skogix.treesitter"
require "skogix.autopairs"
require "skogix.comment"
require "skogix.nvim-tree"
require "skogix.bufferline"
require "skogix.lualine"
require "skogix.toggleterm"
require "skogix.project"
require "skogix.illuminate"
require "skogix.indentline"
require "skogix.alpha"
require "skogix.lsp"
require "skogix.dap"
require "skogix.telekasten"
require "skogix.whichkey"
require "skogix.hop"
require "skogix.telescope-file-browser"
require "skogix.ionide"
