-- { 'tpope/vim-surround' },
-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()" --}}}
<<<<<<< HEAD
require "skogix.impatient"
require "skogix.options"
require "skogix.plugins"
require "skogix.mappings"
require "skogix.autocommands"
require "skogix.colorscheme"
require "skogix.cmp"
require "skogix.telescope"
require "skogix.gitsigns"
require "skogix.treesitter"
require "skogix.autopairs"
require "skogix.comment"
require "skogix.nvim-tree"
require "skogix.bufferline"
require "skogix.lualine"
require "skogix.toggleterm"
require "skogix.project"
require "skogix.illuminate"
require "skogix.indentline"
require "skogix.alpha"
require "skogix.lsp"
require "skogix.dap"
require "skogix.telekasten"
require "skogix.whichkey"
require "skogix.hop"
require "skogix.telescope-file-browser"
require "skogix.ionide"
=======
require "user.impatient"
require "user.options"
require "user.plugins"
require "user.mappings"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.illuminate"
require "user.indentline"
require "user.alpha"
-- require "user.lsp"
require "user.dap"
require "user.telekasten"
require "user.whichkey"
require "user.hop"
require "user.telescope-file-browser"
>>>>>>> 855ed6b (.)
